增加putimage_rotatetransparent方法
wysaid/xege pull request #48
Opened 2020-10-08 03:09 UTC by royqh1979

目前xege库中没有比较方便的能够旋转并忽略背景进行复制的方法（putimage_rotate无法忽略背景,putimage_transparent无法旋转）
因此我增加了putimage_rotatetransparent方法及其实现，相关的api说明，和demo实例程序。

2020-10-08 09:18 UTC, wysaid requested changes
有一些格式上的问题， 麻烦修一下吧~~~

2020-10-08 09:18 UTC, wysaid commented on demo/egerotatetransparent.cpp
> +	int points[6];
demo 这个对齐稍微有点乱啊， 用vs之类的自动格式化一下吧

2020-10-08 09:18 UTC, wysaid commented on src/ege.h
> +        PIMAGE imgdest,/* handle to dest, NULL means the SCREEN */
这个方法和1002行那个重载方法， 对齐方式不一样， 格式化一下吧

2020-10-08 09:18 UTC, wysaid commented on src/image.cpp
> +			if (c !=crTransparent) {
这两个函数也格式化一下吧， 风格不大统一， `=` 左右有时候有空格有时候没有， 建议全都保持一样的风格， 都加空格。   别的符号也是一样， `,`后面跟一个空格.

2020-10-08 09:18 UTC, wysaid commented on src/image.cpp
> +		0,0,imgsrc->getwidth(),imgsrc->getheight(),
同上

2020-10-08 09:56 UTC, royqh1979 commented
请问格式化有啥要求？缩进用tab还是空格？
有没有astyle或者clion的格式化配置之类的东西？


Wang Yang <notifications@github.com> 于2020年10月8日周四 下午5:19写道：

> *@wysaid* requested changes on this pull request.
>
> 有一些格式上的问题， 麻烦修一下吧~~~
> ------------------------------
>
> In demo/egerotatetransparent.cpp
> <https://github.com/wysaid/xege/pull/48#discussion_r501569240>:
>
> > @@ -0,0 +1,31 @@
>
> +#include <graphics.h>
>
> +#include "ege_head.h"
>
> +#include <math.h>
>
> +
>
> +int main()
>
> +{
>
> +	int points[6];
>
>
> demo 这个对齐稍微有点乱啊， 用vs之类的自动格式化一下吧
> ------------------------------
>
> In src/ege.h
> <https://github.com/wysaid/xege/pull/48#discussion_r501569684>:
>
> > -
>
> +
>
> +int EGEAPI putimage_rotatetransparent(
>
> +    PIMAGE imgdest,/* handle to dest, NULL means the SCREEN  */
>
> +    PIMAGE imgsrc,/* handle to source */
>
> +    int xCenterDest,/* x-coord of rotation center in dest */
>
> +    int yCenterDest,/* y-coord of rotation center in dest */
>
> +    int xCenterSrc, /* x-coord of rotation center in source */
>
> +    int yCenterSrc,/* y-coord of rotation center in source */
>
> +    color_t crTransparent, /* color to make transparent */
>
> +    float radian, /* rotation angle (clockwise, in radian) */
>
> +    float zoom=1.0 /* zoom factor */
>
> +);
>
> +
>
> +int EGEAPI putimage_rotatetransparent(
>
> +        PIMAGE imgdest,/* handle to dest, NULL means the SCREEN */
>
>
> 这个方法和1002行那个重载方法， 对齐方式不一样， 格式化一下吧
> ------------------------------
>
> In src/image.cpp
> <https://github.com/wysaid/xege/pull/48#discussion_r501570632>:
>
> > +	int zoomed_height=heightSrc*zoom;
>
> +	int zoomed_center_x = (xCenterSrc-xOriginSrc)*zoom;
>
> +	int zoomed_center_y = (yCenterSrc-yOriginSrc)*zoom;
>
> +	/* zoom */
>
> +	PIMAGE zoomed_img = newimage(zoomed_width,zoomed_height);
>
> +	putimage(zoomed_img,0,0,zoomed_width,zoomed_height,
>
> +		imgsrc,xOriginSrc,yOriginSrc,widthSrc,heightSrc,SRCCOPY);
>
> +	
>
> +	/* rotation */
>
> +
>
> +	for (int x=0;x<zoomed_width;x++) {
>
> +		for (int y=0;y<zoomed_height;y++) {
>
> +			color_t c = getpixel(x,y,zoomed_img);
>
> +			double src_x = ((x-zoomed_center_x)*cos(radian)-(y-zoomed_center_y)*sin(radian))+xCenterDest;
>
> +			double src_y=((x-zoomed_center_x)*sin(radian)+(y-zoomed_center_y)*cos(radian))+yCenterDest;
>
> +			if (c !=crTransparent) {
>
>
> 这两个函数也格式化一下吧， 风格不大统一， = 左右有时候有空格有时候没有， 建议全都保持一样的风格， 都加空格。 别的符号也是一样， ,
> 后面跟一个空格.
> ------------------------------
>
> In src/image.cpp
> <https://github.com/wysaid/xege/pull/48#discussion_r501570760>:
>
> > +
>
> +int putimage_rotatetransparent(
>
> +		PIMAGE imgdest,
>
> +		PIMAGE imgsrc,
>
> +		int xCenterDest,
>
> +		int yCenterDest,
>
> +		int xCenterSrc,
>
> +		int yCenterSrc,
>
> +		color_t crTransparent,
>
> +		float radian,
>
> +		float zoom
>
> +	)
>
> +{
>
> +	return putimage_rotatetransparent(imgdest,imgsrc,
>
> +		xCenterDest,yCenterDest,
>
> +		0,0,imgsrc->getwidth(),imgsrc->getheight(),
>
>
> 同上
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/wysaid/xege/pull/48#pullrequestreview-504584399>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACDFGRHRAD4FT44M3U5RB7TSJV7ZFANCNFSM4SIFX6PA>
> .
>

2020-10-08 10:14 UTC, royqh1979 commented
重新格式化了一下

2020-10-08 10:16 UTC, royqh1979 commented
能否统一把代码文件都改成windows EOL啊？有些编辑器会自动把unix EOL变成windows EOL，diff就会显示有大量修改，很麻烦。

2020-10-08 16:48 UTC, wysaid requested changes

2020-10-08 16:48 UTC, wysaid commented on src/image.cpp
> +			double src_y=((x-zoomed_center_x)*sin(radian)+(y-zoomed_center_y)*cos(radian))+yCenterDest;
在网页上看， 这一行跟2606行还是没对齐.... 前面 2601也是.... 囧

2020-10-08 16:49 UTC, wysaid commented
> 能否统一把代码文件都改成windows EOL啊？有些编辑器会自动把unix EOL变成windows EOL，diff就会显示有大量修改，很麻烦。

不是换行的问题， 是你对齐的时候有时候是tab有时候是空格, 都换成空格吧

2020-10-08 17:09 UTC, chirsz-ever commented on src/ege.h
> +    PIMAGE imgsrc,/* handle to source */
`imgsrc` 参数应为 `PCIMAGE` 类型

2020-10-08 17:21 UTC, chirsz-ever commented on src/image.cpp
> +                putpixel(src_x+0.5,src_y+0.5,c,img);
恐有效率问题，建议改成直接操作缓冲区。

2020-10-08 17:21 UTC, chirsz-ever commented
遍历目的区域像素，对源图像进行采样再混合是不是合理些？

2020-10-08 23:13 UTC, royqh1979 commented on src/image.cpp
> +			double src_y=((x-zoomed_center_x)*sin(radian)+(y-zoomed_center_y)*cos(radian))+yCenterDest;
2061行是一条语句分在两行上，不需要缩进吗？

2020-10-08 23:16 UTC, royqh1979 commented
> > 能否统一把代码文件都改成windows EOL啊？有些编辑器会自动把unix EOL变成windows EOL，diff就会显示有大量修改，很麻烦。
> 
> 不是换行的问题， 是你对齐的时候有时候是tab有时候是空格, 都换成空格吧

空格是一个问题，EOL是另一个问题
我用notepad2/devcpp修改代码的时候，保存时会每一行的结尾都会自动保存为windows EOL(/r/n)，而原始代码都是Unix EOL结尾(/n)，这样git diff的时候就会认为*每一行*都有改动。

2020-10-08 23:22 UTC, TheBadZhang commented
> > > 能否统一把代码文件都改成windows EOL啊？有些编辑器会自动把unix EOL变成windows EOL，diff就会显示有大量修改，很麻烦。
> > 
> > 
> > 不是换行的问题， 是你对齐的时候有时候是tab有时候是空格, 都换成空格吧
> 
> 空格是一个问题，EOL是另一个问题
> 我用notepad2/devcpp修改代码的时候，保存时会每一行的结尾都会自动保存为windows EOL(/r/n)，而原始代码都是Unix EOL结尾(/n)，这样git diff的时候就会认为_每一行_都有改动。

Git 应该是可以设置使用 LF 还是 CRLF 的

2020-10-08 23:32 UTC, royqh1979 commented
> > > > 能否统一把代码文件都改成windows EOL啊？有些编辑器会自动把unix EOL变成windows EOL，diff就会显示有大量修改，很麻烦。
> > > 
> > > 
> > > 不是换行的问题， 是你对齐的时候有时候是tab有时候是空格, 都换成空格吧
> > 
> > 
> > 空格是一个问题，EOL是另一个问题
> > 我用notepad2/devcpp修改代码的时候，保存时会每一行的结尾都会自动保存为windows EOL(/r/n)，而原始代码都是Unix EOL结尾(/n)，这样git diff的时候就会认为_每一行_都有改动。
> 
> Git 应该是可以设置使用 LF 还是 CRLF 的

不止这一个项目呀

2020-10-08 23:33 UTC, chirsz-ever commented
> > > 能否统一把代码文件都改成windows EOL啊？有些编辑器会自动把unix EOL变成windows EOL，diff就会显示有大量修改，很麻烦。
> > 
> > 
> > 不是换行的问题， 是你对齐的时候有时候是tab有时候是空格, 都换成空格吧
> 
> 空格是一个问题，EOL是另一个问题
> 我用notepad2/devcpp修改代码的时候，保存时会每一行的结尾都会自动保存为windows EOL(/r/n)，而原始代码都是Unix EOL结尾(/n)，这样git diff的时候就会认为_每一行_都有改动。

```sh
$ git config --global core.autocrlf true
```
详情请阅读 <https://git-scm.com/book/zh/v2/%E8%87%AA%E5%AE%9A%E4%B9%89-Git-%E9%85%8D%E7%BD%AE-Git>

2020-10-08 23:33 UTC, royqh1979 commented
> > 能否统一把代码文件都改成windows EOL啊？有些编辑器会自动把unix EOL变成windows EOL，diff就会显示有大量修改，很麻烦。
> 
> 不是换行的问题， 是你对齐的时候有时候是tab有时候是空格, 都换成空格吧

另外，关于空格/tab的问题，image.cpp里面的putimage_rotatezoom就是tab缩进；
最好能统一处理一下，以后再提交的时候就统一按照这个样式来做

2020-10-09 00:06 UTC, royqh1979 commented
我看了一下，ege.h里面原来都是tab缩进？如果这个提交

> > > > 能否统一把代码文件都改成windows EOL啊？有些编辑器会自动把unix EOL变成windows EOL，diff就会显示有大量修改，很麻烦。
> > > 
> > > 
> > > 不是换行的问题， 是你对齐的时候有时候是tab有时候是空格, 都换成空格吧
> > 
> > 
> > 空格是一个问题，EOL是另一个问题
> > 我用notepad2/devcpp修改代码的时候，保存时会每一行的结尾都会自动保存为windows EOL(/r/n)，而原始代码都是Unix EOL结尾(/n)，这样git diff的时候就会认为_每一行_都有改动。
> 
> ```shell
> $ git config --global core.autocrlf true
> ```
> 
> 详情请阅读 https://git-scm.com/book/zh/v2/%E8%87%AA%E5%AE%9A%E4%B9%89-Git-%E9%85%8D%E7%BD%AE-Git

手上不止这一个项目呀。能否把设置放到这个项目的.gitattribute里？

2020-10-09 00:25 UTC, royqh1979 commented on src/image.cpp
> +                putpixel(src_x+0.5,src_y+0.5,c,img);
我看了一下putpixel的实现，就是多了一个PIMAGE img = CONVERT_IMAGE(pimg);
剩下的增加m_vpt.left和m_vpt.top，判断是否在viewport里，都是必须要做的，重复写一遍有必要吗？

2020-10-11 12:40 UTC, merged