增加主控台系列函数
wysaid/xege pull request #64
Opened 2020-12-10 00:23 UTC by royqh1979

用户在程序中可以使用init_console()创建和显示主控台窗口，close_console()关闭主控台窗口。

不再需要在编译程序时指定了

2020-12-10 07:26 UTC, wysaid requested changes
@royqh1979 看看吧

2020-12-10 07:26 UTC, wysaid commented on src/egegapi.cpp
> +	hInput=
这个对齐为啥这么奇怪呢... 这里为啥要换行呢

2020-12-10 07:26 UTC, wysaid commented on src/egegapi.cpp
> +    FILE *hf;
这里对齐也很奇怪， 这个文件里面， 符号的左右有时候有空格有时候没有， 统一一下吧

2020-12-10 07:26 UTC, wysaid commented on src/ege.h
> +#if _MSC_VER < 1300
是不是写反了， 应该是 `>` 吧 ?

2020-12-10 11:43 UTC, royqh1979 commented on src/ege.h
> +#if _MSC_VER < 1300
是的，修改了，增加_MSC_VC6宏定义，然后后面直接用这个宏来判断

2020-12-10 11:51 UTC, royqh1979 commented on src/egegapi.cpp
> +    FILE *hf;
ok

2021-01-04 12:53 UTC, merged

2021-01-18 15:54 UTC, chirsz-ever commented on src/egegapi.cpp
> +	hCrt=_open_osfhandle((long)hInput,_O_TEXT);
这里应该使用 `HANDLE` 而非 `long`